const appname = "JayMart";
const appversion = "Version 1.0.0";
const credits = "@Jay Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "**********";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginwith = "Log in with";
const retypePassword = "Retype Password";
const name = 'Name';
const nameHint = "Jay devs";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";

const home = 'Home',
    categories = 'Categories',
    cart = 'Cart',
    account = "account";
const searchAnything = 'Search anything...',
    todayDeal = "Today's Deal",
    flashSale = 'Flash Sale',
    topSellers = 'Top Sellers',
    brand = "Brand",
    topCategories = 'Top Categories',
    featuredCategories = 'Featured Categories',
    womenDress=" Women Dress",
    girlsWatches='Girls Watches',
    mobilePhones='Mobile Phones',
    boysGlasses='Boys Glasses',
    tShirts='TShirts',
    girlsDress='Girls Dress',
    featuredProduct='Featured Product'

;
